### PR TITLE
Added TicTacToe

### PR DESCRIPTION
**Pull request by Chandler-Kluser**
As requested in [this PR](https://github.com/vircon32/ConsoleSoftware/pull/3#issuecomment-1244385239), adding simple tic tac toe game.

Build instructions in README file.

Keep the great work!

### CODE REVIEW

**Comment by vircon32** [comment]
Thank you Chandler, your game is nice for having done it only in 1 day! I have added a couple of commits to adapt the game folder to the way this repo is going to work:

- On one hand I will be including the playable .v32 roms, so that people can easily try games (not everybody will have the knowledge to build them).
- Oh the other, I adapted screenshots to real size (640 x 360). Also, since I played the game a bit, I replaced the gameplay screenshot (which showed the board empty) to show how it looks during an actual game.

I have a question: should we remove the .vscode folder, or is that needed? I saw you removed it the other time. If needed I could also add .vscode to gitignore.

**Comment by Chandler-Kluser** [comment]
Sorry, the .vscode should not have been added as well as the build folder, this should have been put in the .gitignore file.

But feel free to decide whether to keep or not, it doesn't matter for me.

**Comment by Chandler-Kluser** [comment]
The .v32 rom instead of being in `build` folder could be provided in the repository release tab

**Comment by vircon32** [comment]
> The .v32 rom instead of being in `build` folder could be provided in the repository release tab

You are right. I have still not made a decision about this, I'm not sure if the release system will work well once if at some point there are a large number of projects here. I will leave the binaries for now, we can always change that in the future if needed.

**Pull request merged**
